-
  branches:
    only:
      - master

  configuration: Release

  install:
    - ps: .\src\.nuget\nuget.exe restore .\src\MvcTables.sln

  assembly_info:
    patch: true
  
  build:
    publish_nuget: true

  deploy:
    provider: NuGet
    api_key:
      secure: 8imu4ltmARd9TSapCxG53y7ysUZYyFS1SJPqvEMJjm4uYFZmQhGPto8AWRqDoweh
    skip_symbols: true
    artifact: /.*\.nupkg/

-
  # "fall back" configuration for all other branches
  install:
    - ps: .\src\.nuget\nuget.exe restore .\src\MvcTables.sln